import React from 'react'
import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { Poppins, DM_Sans } from 'next/font/google'
import StoreProvider from '@/app/stroreProvider'
import Header from '@/app/components/Header'
import theme from '../utils/theme'
import './globals.css'

const poppins = Poppins({
   weight: ['300', '400', '500', '700', '800', '900'],
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-poppins',
})

const dmSans = DM_Sans({
   weight: ['300', '400', '500', '700', '800', '900'],
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-dm-sans',
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
               <StoreProvider>
                  <body className={`${dmSans.variable} ${poppins.variable}`}>
                     <Header />
                     {children}
                  </body>
               </StoreProvider>
            </ThemeProvider>
         </AppRouterCacheProvider>
      </html>
   )
}
